spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    # 指定类的日志级别
#    com.xd.sell.SellApplicationTests: debug
##  level: debug
